### ISSUE TITLE
Is there any way to return an error message from a found virus using mod_sftp

### ISSUE THREAD

**Issue by offsides** [jbenden/mod_clamav#14]
When uploading a virus-laden file with FTP, it returns a 550 code with an error message about the virus that is found.  With mod_sftp using SFTP there is no message, the file is just silently discarded.  Is there any way to return a similar message to the SFTP session to notify the uploader that the upload failed?  Even using SCP, the exit code is 0, so there's no indication that the copy failed.  I'll take a look at the code as well, but it seems that this is a significant impediment to being able to use mod_clamav with mod_sftp.

**Comment by Castaglia** [comment]
The SSH RFCs define a fixed set of error _codes_ (numeric values with specific semantics); these are what are transmitted to clients in cases of errors:
* https://github.com/proftpd/proftpd/blob/master/contrib/mod_sftp/fxp.c#L150
 
These specifications don't really have any way of transmitting freeform text messages in the case of errors, unfortunately.  There are things such as the [DEBUG SSH message](https://www.rfc-editor.org/rfc/rfc4253#section-11.3), yes -- but client applications are free to ignore these messages, and not to display them to the end user.

**Comment by offsides** [comment]
OK.  I'm not sure if SFTP is getting the correct code (I need to test programmaticaly rather than interactively), but scp is exiting 0 when transferring an infected file, which probably isn't correct.  I'll see if I can check what the SFTP return code is.

**Comment by offsides** [comment]
OK, I just did a test and it appears that even when a virus is found, SFTP is returning status code 0, meaning all is well.  I'll take a look and see if I can figure this out, but having dug some of this code already I'm a little lost with all of the complications of SFTP. :)

**Comment by offsides** [comment]
Looking at the code between mod_clamav and mod_sftp, I *think* that the issue is that mod_clamav only sends a response if the protocol is ftp/ftps, and otherwise clamav_fsio_close only sends a non-zero if there was a clamav error, but a successful scan that finds a virus returns a non-negative value with no error, so it just returns 0.  Which is then interpreted by mod_sftp as a successful transfer.  So I think that there needs to be additional logic in mod_clamav to return non-zero and set errno properly so that fxp.c sees that the transfer failed.  But I don't know the rationale behind how mod_clamav does things well enough to know what the right way to do that is.  That said, I'll keep digging and see if I can come up with something that works.

**Comment by offsides** [comment]
I don't know if this is a viable patch overall, but it does appear to make things work properly for mod_sftp and is nice and simple:
```
--- contrib/mod_clamav.c.orig   2023-05-16 11:53:12.233439274 -0400
+++ contrib/mod_clamav.c        2023-05-16 11:20:00.199902786 -0400
@@ -583,6 +584,9 @@
     }
     errno = EPERM;
     return -1;
+  } else if (res) {
+    errno = EPERM;
+    return -1;
   }
 
   if (clam_errno == 0)
```
I also tried adding a response message to send to the sftp client with pr_response_add_err(), but it looks like the subsequent call in fxp_handle_close overwrites that message and so I got nothing.  If there's a better way to do that, I'm all ears.

**Comment by offsides** [comment]
Actually, this patch is better - otherwise SFTP gets a failure message if there was an error scanning the file even if FailSafe is off.
```
--- contrib/mod_clamav.c.orig   2023-05-16 11:53:12.233439274 -0400
+++ contrib/mod_clamav.c        2023-05-16 11:20:00.199902786 -0400
@@ -578,7 +581,10 @@
                    MOD_CLAMAV_VERSION ": notice    : unlink() failed (%d): %s",
                    errno, strerror(errno));
       }
+      errno = EPERM;
+      return -1;
     }
+  } else if (res) {
     errno = EPERM;
     return -1;
   }
```

**Comment by offsides** [comment]
> There are things such as the [DEBUG SSH message](https://www.rfc-editor.org/rfc/rfc4253#section-11.3), yes -- but client applications are free to ignore these messages, and not to display them to the end user.

Is there a function in mod_sftp to send these messages?  I see code to receive them, but not to send.  I'm curious if I could get it to send one with a notice about the detected virus.

**Comment by offsides** [comment]
After a bit more digging, I could tell that Proftpd handled receiving DEBUG messages, but not sending them, so I wrote a function to do so and just submitted a pull request.  If that gets merged, then I'll add a pull request here to send such a message, though most SFTP clients will probably ignore it anyway.

**Comment by jbenden** [comment]
See: #17
