### ISSUE TITLE
FTP Sessions become unusable after a virus is detected

### ISSUE THREAD

**Issue by offsides** [jbenden/mod_clamav#15]
With SFTP sessions, after uploading a file with a virus the session continues to be usable normally.  But with FTP sessions, after uploading a file with a virus and getting the 550 response, the next thing I do returns "ftp: connect: Connection refused", and then further commands sent to the server hang.  I did notice that when I tried toggling passive mode and then doing a dir it issued the passive commands and didn't executed the dir, so I suspect that something is getting either stuck or not properly flushed.  This is with the latest proftpd master, so that might also have something to do with it since mod_clamav is rather old.  Any help would be appreciated.

**Comment by offsides** [comment]
Additional info: Here's what happens if I upload a virus and then just exit:
```
ftp> put eicar.com
local: eicar.com remote: eicar.com
227 Entering Passive Mode (127,0,0,1,144,163).
150 Opening BINARY mode data connection for eicar.com
550 Virus Detected and Removed: Eicar-Signature
69 bytes sent in 4.2e-05 secs (1642.86 Kbytes/sec)
ftp> exit
550 eicar.com: Operation not permitted
```
So it looks like some buffer isn't being cleared before the next command is entered.

**Comment by offsides** [comment]
OK, I found the problem - on line 889 of mod_clamav.c, it uses pr_response_send, which sends the 550 error message about virus detected and removed.  But the FTP session ALSO sends a 550 error code, which causes problems on the client side.  The solution is to change it to pr_response_add_err, which prints it as '550-Virus Detected and Removed...', thus causing the FTP client to expect another line with the final response code.

**Comment by jbenden** [comment]
See: #17
