### ISSUE TITLE
mod_clamav/0.13 + proftpd 1.3.5a - Not scanned files

### ISSUE THREAD

**Issue by ufoboss** [jbenden/mod_clamav#5]
Hello!
Sorry for my english 

Please help solve the a problem.
After installing and configure the mod_clamav/0.13 + proftpd 1.3.5a is not working virus scanning of files transferred... In the journal ([proftpd.log (-n -d 5)](https://github.com/jbenden/mod_clamav/files/98391/proftpd_log.txt)) there is no mention in the anti-virus scan, and all infected files sent bypassed anti-virus scanning.
My current [proftpd.conf](https://github.com/jbenden/mod_clamav/files/98366/proftpd.conf.txt) in attached file on this message.

====================================================================
#proftpd -vv
ProFTPD Version: 1.3.5a (maint)
  Scoreboard Version: 01040003
  Built: Wed Jan 20 2016 22:39:06 EET

Loaded modules:
  mod_clamav/0.13
  mod_ctrls_admin/0.9.7
  mod_ban/0.6.2
  mod_ldap/2.9.4
  mod_lang/1.0
  mod_ctrls/0.9.5
  mod_auth_pam/1.2
  mod_ident/1.0
  mod_dso/0.5
  mod_facts/0.3
  mod_delay/0.7
  mod_site.c
  mod_log.c
  mod_ls.c
  mod_auth.c
  mod_auth_file/1.0
  mod_auth_unix.c
  mod_rlimit/1.0
  mod_xfer.c
  mod_core.c
#========================================================================

**Comment by ufoboss** [comment]
Clamav.conf:
...
FixStaleSocket yes
TCPSocket 3310
TCPAddr 127.0.0.1
...

#sockstat -4 | grep clamav
clamav   clamd      62243 5  tcp4   127.0.0.1:3310        *:*

**Comment by jbenden** [comment]
On Thu, 2016-01-21 at 02:29 -0800, ufoboss wrote:
> Clamav.conf:
> ...
> FixStaleSocket yes
> TCPSocket 3310
> TCPAddr 127.0.0.1
> ...
> 
> #sockstat -4 | grep clamav
> clamav clamd 62243 5 tcp4 127.0.0.1:3310 :
> 

Hello,

I have committed a number of source-code changes to the `mod_clamav`
module, one of which causes critical failure on recent ProFTPD versions.
Additionally, I have added a number of debugging additions. It is
important that these changes be applied to your local installation.
While you do not have a yet working `mod_clamav` environment, you
**will** have problems later, without these changes, being present with
your full ProFTPD installation.

From the two attachments provided, I am unable to help with debugging. I
suggest that you do the following to collect detailed information:

1. Shut down any running instances of ProFTPD.
2. Ensure that a running ClamAV scanner exists.
3. Apply the latest `mod_clamav` source code to your ProFTPD source
code.
4. Ensure to re-build all ProFTPD with `mod_clamav` source code.
5. Run ProFTPD in very verbose output mode, from the shell, as follows
(from within the build tree):

    $ ./proftpd -q -d20

*NOTE*: It may be necessary to specify your configuration file in the
shell command. It is specified using the `-c` option, which takes a
single argument; the full path to the configuration file it should use.

If the verbose output does not help diagnose the problem you are
experiencing, then please share the output for additional help in
debugging.

Thank you,
-Joseph Benden

**Comment by jbenden** [comment]
Closing issue as no response has been received.
