### ISSUE TITLE
lstat() failed: No such file or directory. ERROR

### ISSUE THREAD

**Issue by pilchita** [jbenden/mod_clamav#9]
Hello,

I install mod_clamav, in local mode it works fine, but I try to connect to a remote server I see this error:

#######

mod_clamav/0.11rc: Clamd Error: /home/testuser/Invoice INV0000653.doc: lstat() failed: No such file or directory. ERROR

/opt/sbin/proftpd -v
ProFTPD Version 1.3.5a

ProFTPD Version: 1.3.5a (maint)
  Scoreboard Version: 01040003
  Built: mar nov 3 2015 13:00:21 ART

Loaded modules:
  mod_ctrls/0.9.5
  mod_cap/1.1
  mod_ban/0.6.2
  mod_geoip/0.6
  mod_sql_mysql/4.0.8
  mod_sql/4.3
  mod_ldap/2.9.4
  mod_clamav.c
  mod_tls/2.6
  mod_auth_pam/1.2
  mod_ident/1.0
  mod_facts/0.3
  mod_delay/0.7
  mod_site.c
  mod_log.c
  mod_ls.c
  mod_auth.c
  mod_auth_file/1.0
  mod_auth_unix.c
  mod_rlimit/1.0
  mod_xfer.c
  mod_core.c

==> /opt/etc/proftpd.conf

<IfModule mod_clamav.c>
ClamAV on
ClamServer REMOTE_SERVER
ClamPort 3310
</IfModule>

==> Local Mode is work fine

<IfModule mod_clamav.c>
    ClamAV on
    ClamServer 127.0.0.1
    ClamPort 3310
</IfModule>

Estado:    Comenzando la subida de /home/x/x/InvoiceXXM8566596.doc
Estado:    Retrieving directory listing of "/"...
Comando:    PASV
Respuesta:    227 Entering Passive Mode (x,x,x,x,x,x).
Comando:    LIST
Respuesta:    150 Opening BINARY mode data connection for file list
Respuesta:    226 Transfer complete
Comando:    PASV
Respuesta:    227 Entering Passive Mode (x,x,x,x,x,x).
Comando:    STOR InvoiceXXM8566596.doc
Respuesta:    150 Opening BINARY mode data connection for InvoiceXXM8566596.doc
Respuesta:    550 Virus Detected and Removed: Img.Dropper.PhishingLure-6376446-0

 
any ideas?

Regards.!!

aloha.

**Comment by jbenden** [comment]
Hello,

When using a remote server to scan files, you must use the setting `ClamStream on` or the remote server will be unable to access the file.

A locally working example configuration is:

```
ClamAV on
ClamServer 127.0.0.1
ClamPort 3310
ClamStream on
```

Best Regards,
-Joe
